version : '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Cas2020
    ports:
      - 5672:5672
      - 15672:15672

  database:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Cas2020
      MYSQL_USER: admin
      MYSQL_PASSWORD: Cas2020
      MYSQL_DATABASE: cascloud
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
    driver: local